/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Control.ControllerAlterarExcluirUsuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1
 */
public class JanelaAlterarExcluirUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JanelaAlterarExcluirUsuario
     */
    private JTable tabela;
    private DefaultTableModel modelo = new DefaultTableModel();
    private ControllerAlterarExcluirUsuario controller;

    public JanelaAlterarExcluirUsuario(ControllerAlterarExcluirUsuario controller) {
        initComponents();
        this.controller = controller;
        criarTabela();
        campoBusca.addActionListener(controller);
        botaoExcluir.addActionListener(controller);
        botãoAlterar.addActionListener(controller);
        
        rolagem.setViewportView(tabela);
    }

    private void criarTabela() {
        tabela = new JTable(modelo);
        tabela.addMouseListener(controller);
        modelo.addColumn("Code");
        modelo.addColumn("Name");
        modelo.addColumn("Login");
       // modelo.addColumn("Password");
        tabela.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(80);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(50);
       // tabela.getColumnModel().getColumn(3).setPreferredWidth(50);

    }
    
     public void preencherTabela(ResultSet res){
    
    ResultSet rs = res;
    modelo.setNumRows(0);
    Object[] obj = new Object[3];
        try {
     
            rs.next();
            do{
            obj[0] = rs.getObject("Codigo");
            obj[1] = rs.getObject("Nome");
            obj[2] = rs.getObject("Login");
           // obj[3] = rs.getObject("Password");
            modelo.addRow(obj);
            }while(rs.next());
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problem to access the bank!");
        }
     }

    public JButton getBotaoExcluir() {
        return botaoExcluir;
    }

    public JButton getBotãoAlterar() {
        return botãoAlterar;
    }

    public JTextField getCampoBusca() {
        return campoBusca;
    }
    
    public JTable getTable(){
    return tabela;
    }
    
    public JButton getAlterar(){
    return botãoAlterar;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBusca = new javax.swing.JLabel();
        campoBusca = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        rolagem = new javax.swing.JScrollPane();
        botãoAlterar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:: NatProDB - Alterar/Excluir Usuário::.");

        labelBusca.setText("Insert Login:");

        campoBusca.setFont(new java.awt.Font("Times New Roman", 0, 12));

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Users", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        botãoAlterar.setText("Change");

        botaoExcluir.setText("Exlcude");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(labelBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 519, Short.MAX_VALUE)
                .addComponent(botãoAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluir)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBusca)
                    .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botãoAlterar)
                    .addComponent(botaoExcluir))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botãoAlterar;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBusca;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane rolagem;
    // End of variables declaration//GEN-END:variables
}
