/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaCadastrarMolecula.java
 *
 * Created on 28/02/2012, 21:20:01
 */
package view;

import Control.ControllerAlteraMolecula;
import Control.ControllerCadastraMolecula;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author PETENGS
 */
public class JanelaAlterarMolecula extends javax.swing.JFrame {

    /** Creates new form JanelaCadastrarMolecula */
    public JanelaAlterarMolecula(ControllerAlteraMolecula control) {
        initComponents();
        botaoCancelar.addActionListener(control);
        botaoOk.addActionListener(control);
        comboBox.addActionListener(control);
//        comboAltera.addActionListener(control);
        campoEspecie.setEditable(false);
        campoFamilia.setEditable(false);
        campoFormulaMolecular.setEditable(true);
        campoHBA.setEditable(true);
        campoHBD.setEditable(true);
        campoLogP.setEditable(true);
        campoNome.setEditable(true);
        campoNomeIupac.setEditable(true);
        campoPesoMolecular.setEditable(true);
        campoSmile.setEditable(true);
        areaAtividadeBio.setEditable(true);
        areaLocalização.setEditable(true);
        AreaReferencia.setEditable(true);
        campocodigo.setEditable(true);
    }

//    public JComboBox getComboAltera() {
  //      return comboAltera;
   // }
    
    public JComboBox getComboBox() {
        return comboBox;
    }

    public JTextArea getAreaReferencia() {
        return AreaReferencia;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCodigo = new javax.swing.JLabel();
        campocodigo = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoNomeIupac = new javax.swing.JTextField();
        labelNomeIupac = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox();
        labelFamilia = new javax.swing.JLabel();
        campoFamilia = new javax.swing.JTextField();
        labelEspecie = new javax.swing.JLabel();
        campoEspecie = new javax.swing.JTextField();
        labelAtividadeBio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaAtividadeBio = new javax.swing.JTextArea();
        labelLocalizacao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaLocalização = new javax.swing.JTextArea();
        fórmulaMolecular = new javax.swing.JLabel();
        campoFormulaMolecular = new javax.swing.JTextField();
        pesoMoelcular = new javax.swing.JLabel();
        campoPesoMolecular = new javax.swing.JTextField();
        labelLog = new javax.swing.JLabel();
        campoLogP = new javax.swing.JTextField();
        labelReferencia = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AreaReferencia = new javax.swing.JTextArea();
        botaoOk = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        labelSmile = new javax.swing.JLabel();
        campoSmile = new javax.swing.JTextField();
        labelSmile1 = new javax.swing.JLabel();
        campoHBA = new javax.swing.JTextField();
        labelHBD = new javax.swing.JLabel();
        campoHBD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:: NatProDB::. - Alterar Molécula");
        setResizable(false);

        labelCodigo.setText("Code");

        labelNome.setText("Name:");

        labelNomeIupac.setText("IUPAC's Name:");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sintetic", "Semi-Sintetic", "Natural" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        labelFamilia.setText("Family:");

        campoFamilia.setFont(new java.awt.Font("Tahoma", 2, 11));

        labelEspecie.setText("Specie:");

        campoEspecie.setFont(campoEspecie.getFont().deriveFont((campoEspecie.getFont().getStyle() | java.awt.Font.ITALIC)));

        labelAtividadeBio.setText("Biological Activity:");

        areaAtividadeBio.setColumns(20);
        areaAtividadeBio.setRows(5);
        jScrollPane1.setViewportView(areaAtividadeBio);

        labelLocalizacao.setText("Location:");

        areaLocalização.setColumns(20);
        areaLocalização.setRows(5);
        jScrollPane2.setViewportView(areaLocalização);

        fórmulaMolecular.setText("Molecular Formula:");

        pesoMoelcular.setText("Molecular Mass (Da):");

        labelLog.setText("CLogP:");

        labelReferencia.setText("References:");

        AreaReferencia.setColumns(20);
        AreaReferencia.setRows(5);
        jScrollPane3.setViewportView(AreaReferencia);

        botaoOk.setText("OK");

        botaoCancelar.setText("Cancelar");

        labelSmile.setText("Smile: ");

        labelSmile1.setText("HBA:");

        labelHBD.setText("HBD:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelSmile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSmile, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(labelSmile1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoHBA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelAtividadeBio)
                            .addGap(510, 510, 510))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelFamilia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campoFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(labelEspecie)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campoEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelCodigo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campocodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(labelNomeIupac)
                                    .addGap(18, 18, 18)
                                    .addComponent(campoNomeIupac, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelHBD)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoHBD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(botaoOk)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botaoCancelar))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(fórmulaMolecular)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoFormulaMolecular, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pesoMoelcular)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoPesoMolecular, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelLog)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoLogP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(82, 82, 82)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(campocodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomeIupac)
                    .addComponent(campoNomeIupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFamilia)
                    .addComponent(campoFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEspecie)
                    .addComponent(campoEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSmile)
                    .addComponent(campoSmile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSmile1)
                    .addComponent(campoHBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHBD)
                    .addComponent(campoHBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelAtividadeBio)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelLocalizacao))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fórmulaMolecular)
                    .addComponent(campoFormulaMolecular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesoMoelcular)
                    .addComponent(campoPesoMolecular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLog)
                    .addComponent(campoLogP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelReferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoOk)
                    .addComponent(botaoCancelar))
                .addGap(282, 282, 282))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxActionPerformed

    public JButton getBotaoCancelar() {
        return botaoCancelar;
    }

    public JButton getBotaoOk() {
        return botaoOk;
    }

    public String getCodigo() {
        return campocodigo.getText();
    }

    public String getNome() {
        return campoNome.getText();
    }
    public String getNomeiupac() {
        return campoNomeIupac.getText();
    }
    public String getFamilia() {
        return campoFamilia.getText();
    }

    public JTextField getCampoFormulaMolecular() {
        return campoFormulaMolecular;
    }

    public JTextField getCampoNome() {
        return campoNome;
    }

    public JTextField getCampoNomeIupac() {
        return campoNomeIupac;
    }

    public JTextField getCampoHBA() {
        return campoHBA;
    }

    public JTextField getCampoHBD() {
        return campoHBD;
    }

    public JTextField getCampoSmile() {
        return campoSmile;
    }

    public JTextField getCampocodigo() {
        return campocodigo;
    }

    public String getEspecie() {
        return campoEspecie.getText();
    }

    public JTextArea getAreaAtividadeBio() {
        return areaAtividadeBio;
    }

    public JTextArea getAreaLocalização() {
        return areaLocalização;
    }

    public JTextField getCampoEspecie() {
        return campoEspecie;
    }

    public JTextField getCampoFamilia() {
        return campoFamilia;
    }
    public String getAtividadebiologica() {
        return areaAtividadeBio.getText();
    }
    public String getLocalizacao() {
        return areaLocalização.getText();
    }
    public String getFormulaMolecular() {
        return campoFormulaMolecular.getText();
    }
    public float getPesoMolecular() {
        float peso;
        peso = Float.parseFloat(campoPesoMolecular.getText()); 
        return peso;
    }
    public String getSmile(){
    return campoSmile.getText();
    }
    
    public int getHba(){
    int hba;
    hba = Integer.parseInt(campoHBA.getText());
    return hba;
    }
    
    public int getHbd(){
    int hbd;
    hbd = Integer.parseInt(campoHBD.getText());
    return hbd;
    }
    public float getLogp() {
        float log;
        log= Float.parseFloat(campoLogP.getText()); 
        return log;
    }
    public String getReferencia() {
        return AreaReferencia.getText();
    }

    public JTextField getCampoLogP() {
        return campoLogP;
    }

    public JTextField getCampoPesoMolecular() {
        return campoPesoMolecular;
    }
    public String getTipo(){
    return (String) comboBox.getSelectedItem();
    }

   // public JButton getBotãoCarregar() {
     //   return botãoCarregar;
    //}
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaReferencia;
    private javax.swing.JTextArea areaAtividadeBio;
    private javax.swing.JTextArea areaLocalização;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoOk;
    private javax.swing.JTextField campoEspecie;
    private javax.swing.JTextField campoFamilia;
    private javax.swing.JTextField campoFormulaMolecular;
    private javax.swing.JTextField campoHBA;
    private javax.swing.JTextField campoHBD;
    private javax.swing.JTextField campoLogP;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeIupac;
    private javax.swing.JTextField campoPesoMolecular;
    private javax.swing.JTextField campoSmile;
    private javax.swing.JTextField campocodigo;
    private javax.swing.JComboBox comboBox;
    private javax.swing.JLabel fórmulaMolecular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAtividadeBio;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelEspecie;
    private javax.swing.JLabel labelFamilia;
    private javax.swing.JLabel labelHBD;
    private javax.swing.JLabel labelLocalizacao;
    private javax.swing.JLabel labelLog;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNomeIupac;
    private javax.swing.JLabel labelReferencia;
    private javax.swing.JLabel labelSmile;
    private javax.swing.JLabel labelSmile1;
    private javax.swing.JLabel pesoMoelcular;
    // End of variables declaration//GEN-END:variables
}
